apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: javaapplication-deployment
spec:
  selector:
    matchLabels:
      app: javaapplication
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: javaapplication
    spec:
      containers:
        - name: javaapplication
          image: abhinavsingha1/javaapplication:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: javaapplication-ssvc
spec:
  selector:
    app: javaapplication
  ports:
    - protocol: "TCP"
      port: 8080 # This is the port where service will be running on cluster
      targetPort: 8080 # targetPort is same as containerPort
  type: LoadBalancer # type of the service.
